### ISSUE TITLE
What happens to cancelled generator functions? No leaks?

### ISSUE THREAD

**Issue by trusktr** [getify/CAF#15]
I never use generator functions, see maybe I missed didn't. But when you abort, what happens to the function that was waiting in the yield statement? Does it stay waiting on that indefinitely and therefore leak memory?

**Comment by trusktr** [comment]
Or when the generator handler inside CAF loses the reference to the iterator then this allows the gen func to be collected?

**Comment by getify** [comment]
generator instances are held by the iterators. CAF holds the iterator, but once it completes or is canceled, CAF drops the reference to the iterator, which should then have it (and the associated generator instance) easily GC'd.
