### ISSUE TITLE
How to use CAF with Axios' `cancelToken` argument?

### ISSUE THREAD

**Issue by aguynamedben** [getify/CAF#16]
Hi, first off, thanks for this library. I was in the middle of implementing my own async generator-runner when I realized that CAF does exactly what I want and has excellent documentation. It's really, really helpful that you've made this public.

I noticed in the README there are examples showing how to pass `signal` to `fetch()` in order to to abort mid-request. It's awesome that optimization is supported.

Are there any CAF users who are doing a similar thing with Axios? Axios supports a `cancelToken` argument, [documented here](https://github.com/axios/axios#cancellation), but the API seems like it might be slightly off from CAF's.

Here's what Axios does with the `cancelToken` argument: https://github.com/axios/axios/blob/f3cc053fb9feda2c3d5a27513f16e6722a0f9737/lib/adapters/xhr.js#L165

Is there a way I can pass CAF's `signal.pr` to Axios' `cancelToken`? Or wrapped version of `signal.pr`?

CAF and Axios seem to have independent implementations of cancellation, but given that AbstractController is a browser standard, I'm wondering if there's a way to connect the dots between CAF and Axios.

I've been reading the docs and code on both sides carefully, but it's not worth trying and getting it wrong because bailing from an Axios request early is an optimization in my case, not a core requirement. Thanks again for this fantastic library!

–Ben

**Comment by aguynamedben** [comment]
I think this is doing the trick, I'm not sure if there's a more direct way to just pass something to Axios' `cancelToken`, though.

The idea is:
* Listen for CAF to tell us about cancelation
* Forward the cancelation to Axios in the way that Axios documents

```js
  static sync = CAF(function *sync(signal, syncRequest) {
    // Axios cancellation
    const CancelToken = axios.CancelToken;
    const source = CancelToken.source();
    signal.pr.catch((reason) => {
      log.warn(`canceling any outstanding axios requests, reason: ${reason}`);
      source.cancel();
    });

    const response1 = yield axios.get(`/members/${id}`, {
      params: {
        foo: 'bar',
      },
      cancelToken: source.token,
    });

    const response2 = yield axios.get(`/members/${id}`, {
      params: {
        baz: 'bang',
      },
      cancelToken: source.token,
    });
```

**Comment by getify** [comment]
Perhaps try:

```js
yield axios.get(.. , {
   // ..
   cancelToken: new axios.CancelToken(cancel => signal.pr.catch(cancel))
})
```

**Comment by getify** [comment]
Closing for now, hopefully that suggestion worked.

**Comment by aguynamedben** [comment]
Hey, thank you for the reply, and sorry for the delay in reporting back. Here's what I'm doing now, but I will try your method when I get a chance.

```js
    // Forward CAF cancellation to Axios so we can abort a sync mid-request. We
    // don't need to do this in every DataSource, it's an optimization, but
    // maybe there's a way we can generalize it in the main DataSource class one
    // day.
    // https://github.com/getify/CAF/issues/16#issuecomment-640120307
    const CancelToken = axios.CancelToken;
    const source = CancelToken.source();
    signal.pr.catch((reason) => {
      log.debug(`canceling any outstanding axios requests, reason: ${reason}`);
      source.cancel();
    });

    // Get boards ids for member and orgs - /members/{id}
    log.debug(`getting board - /members/${account.upstreamId}`);
    const boardsResponse = yield client.get(`/members/${account.upstreamId}`, {
      params: {
        fields: 'idBoards',
        organizations: 'all',
        organization_fields: 'idBoards',
      },
      cancelToken: source.token,
    });
```

**Comment by aguynamedben** [comment]
Also, thanks again for providing this library, it helped us solve a hard problem.

In other parts of our app we're now playing with similar ideas around wrapping Promises as special-case [Observables](https://rxjs-dev.firebaseapp.com/guide/observable) that return a single value. Async world is crazy!
