### ISSUE TITLE
Feature request: configurable 'this' context

### ISSUE THREAD

**Issue by chrisregnier** [getify/CAF#17]
Thanks for the great little library!
I've been trying to integrate it into some of my work and found that I missing the ability to set 'this' on the generator passed to CAF. So far I've been just using bind on the generator to get around things, but I think things could be improved if CAF allowed a way of setting the bound context.

For an example on my use case:
```
class JobRunner {
  constructor(fooService) {
    this.fooService = fooService;

    // ***  pass in new options with context? ***
    this._runner = CAF(this.run, { context: this });
  }

  *run(signal, ...params ) {
    // do stuff in the generator but still allowed to use 'this' context of the owning class    
  }

  add(...params) {
    const token = new CAF.cancelToken();
    const result = this._runner(token.signal, ...params);
    return { token, result };
  }
}
```

**Comment by getify** [comment]
So you're saying:

```js
x = CAF(someobj.method, { context: someobj });
```

...instead of:

```js
x = CAF(someobj.method.bind(someobj));
```

Did I miss something?

**Comment by chrisregnier** [comment]
Correct.
Using bind creates a new wrapping generator (and requires other support in older browsers)
```
someobj.method.bind(someobj)
``` 
whereas if you could pass in the context then CAF calls the generator function it could just set the context directly like this on [line 194](https://github.com/getify/CAF/blob/3f33c5ca27217ea460903d7febc3587029ef3517/src/caf.src.js#L194)
```
gen.apply(context, args)
```

**Comment by chrisregnier** [comment]
oh I didn't realize you could bind the context to the return runner! Didn't know if that would be safe in case the library tried to use 'this' at all for any of its own stuff.

But ya that'll totally work for me. Thanks
