### ISSUE TITLE
Import Problems — TypeError: (0 , _caf.CAF) is not a function

### ISSUE THREAD

**Issue by aguynamedben** [getify/CAF#25]
What's the most correct way to import CAF in a modern Babel+Webpack+Jest environment?

I upgraded from Webpack 4->5 and it seems I have to change how I'm importing CAF.

It's in a bad situation where I have to choose between code failing and tests working, or code working and tests failing. For a while now I've been using CAF like this:

```js
import CAF from 'caf';

// in some files, using like this
let timeoutToken = CAF.timeout(timeoutMs, timeoutMessage);

// in other files, using like this
const syncWorkspace = CAF(function *syncWorkspace(
  signal: any,
  syncRequest: SyncRequest,
  workspace: any,
) {
  this.syncStatsBreakdown[`workspace-${workspace.gid}`] = {};

  log.info(`workspace ${workspace.gid} - syncing tasks`);
  yield this.syncUserTaskList(signal, syncRequest, workspace);

  log.info(`workspace ${workspace.gid} - syncing projects`);
  yield this.syncWorkspaceProjects(signal, syncRequest, workspace);

  log.info(`workspace ${workspace.gid} - syncing users`);
  yield this.syncUsers(signal, syncRequest, workspace);

  log.info(`workspace ${workspace.gid} - syncing complete`);
});
```

My tests and builds were both happy with that when I was using Webpack 4.

Now, with Webpack 5, it seems I need to alter how I import CAF. But it's somehow in a situation where I can get the code *and* the tests both working. Here are the 2 main ways I'm trying. I've tried variations on these but can't seem to get CAF imported in a way that makes Webpack/Babel/Jest happy.

# import CAF from 'caf';
* Build compiles, but with warnings
![image](https://user-images.githubusercontent.com/107841/117279092-35cbe300-ae16-11eb-9521-9acde1ecc806.png)

* When build runs, it fails
![image](https://user-images.githubusercontent.com/107841/117279188-5136ee00-ae16-11eb-8948-0ad04d62acb6.png)

* When tests run, works fine
![image](https://user-images.githubusercontent.com/107841/117279422-8d6a4e80-ae16-11eb-9c84-899e747cd2ed.png)

# import { CAF } from 'caf';
* Build compiles, with no warnings
![image](https://user-images.githubusercontent.com/107841/117280338-5b0d2100-ae17-11eb-9010-9657a9e52f43.png)

* When build runs, works fine
![image](https://user-images.githubusercontent.com/107841/117280455-76782c00-ae17-11eb-8319-3fc53bddc1c2.png)

* But when tests run, the tests fail.
![image](https://user-images.githubusercontent.com/107841/117280775-c9ea7a00-ae17-11eb-8fac-611fe1d71bcb.png)

My previous environment worked with the first style:
* Webpack 4
* Node 12
* Jest and Babel for tests
* Webpack and Babel for builds

My previous environment seems to require a switch to the second style, but then tests fail:
* Webpack 5
* Node 14
* Jest and Babel for test
* Webpack and Babel for builds

It seems that CAF is using [this trick](https://medium.com/@timoxley/named-exports-as-the-default-export-api-670b1b554f65) to export itself as both a function and namespace. Any recommendations on different things to try? Thank you.

**Comment by aguynamedben** [comment]
I think the Webpack 4->5 upgrade is a red herring. I had also upgraded CAF recently.

CAF 9.0.1 works in all situations for me.
CAF 12.0.1 has the issues where there's a disagreement with how Jest wants me to import vs. my app/Webpack.

I'll let you know if I get anything else figured out. Thanks for working on this library, I love it.

**Comment by getify** [comment]
I would love to help, but I don't personally use Webpack, Jest, etc. I'm surprised at these issues, but I definitely want to help resolve them. Just not quite sure what to do to diagnose, as (from where I sit) these tools do quite a bit of magic that I don't understand.

**Comment by getify** [comment]
I have released CAF 13.0.0 which fixed a regression (for Node 14) with the polyfill loading. I don't know if that's at all related to this issue, but perhaps? If you can re-try with v13, please do so.

**Comment by getify** [comment]
Any further info on this?

**Comment by aguynamedben** [comment]
Hi @getify, sorry for the delay, but I just tested. v13 of CAF didn't blindly fix it, but I figured out what was going on.

We have 2 environments:
* Runtime environment - Electron (Chromium 89 + Node 14)
* Test environment - Jest (Node 14)

Here's what we got working.

**Import style:**
```js
import { CAF } from 'caf';
```

The runtime code "just works" with this, because Chromium 89 is providing AbortController. Node 14 can't provide AbortController when we run Jest, so we have to trick Jest.

**jest.config.js**
```js
const config = {
  runner: '@hypersprite/jest-runner-electron',
  testEnvironment: '@hypersprite/jest-runner-electron/environment',
  testURL: 'http://localhost/',
  moduleNameMapper: {
    '^caf$': '<rootDir>/test/caf',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|ico)$': '<rootDir>/internals/mocks/fileMock.js',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
    // ... more config
  },
  // ... more config
};

module.exports = config;
```

That `^caf$` entry in moduleNameMapper tells Jest "when you go trying to import 'caf', actually import test/caf.js.

**test/caf.js**
```js
// CAF with AbortController polyfill for Node 14
require('../node_modules/caf/dist/abortcontroller-polyfill-only.js');

const CAF = require('../node_modules/caf/src/caf.js');

module.exports = {
  CAF: CAF,
};
```

So, when running Jest (Node 14), we load the AbortController polyfill and expose a module that plays nicely with the import style we want.

When running the code in reality, the AbortController polyfill isn't present because Chromium 89 (part of Electron) provides it.

**Comment by aguynamedben** [comment]
One more thing: thank you so much for documenting the various AbortController polyfill options and import options in the README. I wouldn't have ever figured this out if the docs in the README weren't so great. Thank you!!! 🙏 🙏 🙏

**Comment by MartinMalinda** [comment]
Hello,

If you use CAF directly in the application you can find a way how to import it. I'm using CAF in a library though and people will use different build systems and so I need one universal solution.

https://github.com/MartinMalinda/vue-concurrency/issues/58

I think WP 5 is the odd one here as it works everywhere (browser, WP 4, rollup etc etc) besides there. 

```js
module.exports = Object.assign(CAF,{
	cancelToken,
	delay,
	timeout,
	signalRace,
	signalAll,
	tokenCycle,
});
```

I don't know why `WP 5` does not see CAF as default export. As it's basically

`module.exports = CAF` (+add other functions as properties)

I guess it could be patched like this:

```js
module.exports = Object.assign(CAF,{
	cancelToken,
	delay,
	timeout,
	signalRace,
	signalAll,
	tokenCycle,
        CAF
});
```

Which could make both

`import { CAF } from 'caf'` and `import CAF from 'caf'` work but that seems quite ugly.

I guess someone with specific knowledge of Webpack should help here. I haven't dealt with webpack too much.

**Comment by MartinMalinda** [comment]
Maybe another alternative would be to export like this?

```js
module.exports = { CAF, cancelToken, delay, timeout, signalRace, signalAll, tokenCycle };
```

That would be a breaking change but hopefully it would be universally working?

**Comment by getify** [comment]
See this comment https://github.com/MartinMalinda/vue-concurrency/issues/58#issuecomment-1017940595

I think the better path is to `import CAF from "caf/caf"` than to work-around `import { CAF } from "caf"` not working in some specific (older) version of webpack.

Would like confirmation if that addresses the concern or not. But I think the issue is webpack, not CAF, as far as I can tell.
