### ISSUE TITLE
AbortController not defined using ES Import statements

### ISSUE THREAD

**Issue by Kunal-2001** [getify/CAF#27]
Hey Kyle
I was working on this library and encountered a bug that AbortController is not defined.
It seems that the issue is somewhat related with ES imports statements . I tried using the usual require statements and surprisingly it's working fine.
**Here is the screenshot of the error**
![Screenshot from 2021-06-20 14-09-49](https://user-images.githubusercontent.com/61347506/122667877-dada2980-d1d2-11eb-88f3-ba0f8b4982ae.png)

**Comment by getify** [comment]
Please see: https://github.com/getify/CAF#abortcontroller-polyfill
